import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,readFileSync,rmSync,realpathSync,writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { startServer } from '../service/server.ts';
import { NativeConversations } from '../service/native-conversations.ts';
import { applyDesktopPatches } from '../service/codex-desktop-transport.ts';
import type { NativeTransport,NativeSnapshot,NativeWorkOptions } from '../service/native-conversations.ts';
process.env.MORROW_TEST_MODE='1';
for(const id of ['CODEX','CLAUDE','TRAE'])process.env[`MORROW_TEST_${id}_PATH`]=resolve('tests/fixtures/runtime.mjs');
class FakeNative implements NativeTransport {
  connected=true;cwd='';threadId=randomUUID();sent:Array<{text:string;id?:string;images?:Array<{path:string}>;workOptions?:NativeWorkOptions}>=[];interruptions:string[]=[];answers:any[]=[];failure=false;definitiveFailure=false;readFailure=false;listeners=new Set<(snapshot:NativeSnapshot)=>void>();
  snapshot:NativeSnapshot={threadId:this.threadId,ownerClientId:'actual-app-owner',revision:1,syncedAt:new Date().toISOString(),state:{turns:[],requests:[],currentPermissions:{sandboxPolicy:{type:'readOnly'}}}};
  async connect(){if(!this.connected)throw new Error('App disconnected');}
  status(){return {connected:this.connected,socketPath:'/isolated-fixture.sock',lastError:this.connected?null:'App disconnected'};}
  async listThreads(cwd:string){return realpathSync(cwd)===realpathSync(this.cwd)?[{id:this.threadId,title:'原生任务',cwd,updatedAt:Date.now()}]:[];}
  async readThread(id:string){if(id!==this.threadId)throw new Error('not found');if(!this.connected||this.readFailure)throw new Error('App disconnected');return structuredClone(this.snapshot);}
  async subscribe(id:string,listener:(snapshot:NativeSnapshot)=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener);}
  emit(state:any){this.snapshot={...this.snapshot,revision:this.snapshot.revision+1,syncedAt:new Date().toISOString(),state:{...this.snapshot.state,...state,cwd:this.cwd}};for(const listener of this.listeners)listener(structuredClone(this.snapshot));}
  async sendMessage(id:string,text:string,clientMessageId?:string,images?:Array<{path:string}>,workOptions?:NativeWorkOptions){this.sent.push({text,id:clientMessageId,images,workOptions});if(this.definitiveFailure)throw Object.assign(new Error('native rejection'),{outcomeUnknown:false});if(this.failure)throw new Error('acknowledgement lost');const turnId=randomUUID();this.emit({turns:[...this.snapshot.state.turns,{turnId,status:'inProgress',params:{clientUserMessageId:clientMessageId},items:[{id:randomUUID(),type:'userMessage',clientId:clientMessageId,content:[{type:'text',text},...(images||[]).map(image=>({type:'localImage',path:image.path}))]}]}]});return {turn:{id:turnId}};}
  async interrupt(id:string,turnId:string){this.interruptions.push(turnId);return {ok:true};}
  async respond(id:string,requestId:string|number,kind:any,response:unknown){this.answers.push({id,requestId,kind,response});return {ok:true};}
  close(){this.connected=false;this.listeners.clear();}
}
async function setup(){const root=mkdtempSync(join(tmpdir(),'morrow-native-'));const home=join(root,'home');const path=join(root,'project');mkdirSync(path);const transport=new FakeNative();transport.cwd=path;const service=await startServer({home,port:0,nativeTransport:transport});const token=readFileSync(join(home,'token'),'utf8');const api=async(method:string,path:string,data?:unknown,status=200)=>{const response=await fetch(`http://127.0.0.1:${service.port}${path}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});const result=await response.json();assert.equal(response.status,status,JSON.stringify(result));return result;};const project=await api('POST','/api/projects',{name:'Native',path,goal:'Continue native work'},201);const channel=service.store.all<any>('channels').find(row=>row.projectId===project.id);return {...service,root,transport,api,project,channel,cleanup:async()=>{await service.close();rmSync(root,{recursive:true,force:true});}};}
test('shared background creates one native task per channel and records creation before sending',async()=>{const s=await setup();try{
  let created=0;Object.assign(s.transport,{backgroundReady:true,createThread:async(cwd:string)=>{created++;assert.equal(cwd,s.project.path);s.transport.emit({turns:[]});return s.transport.readThread(s.transport.threadId);}});
  const status=await s.api('GET','/api/native/status');assert.equal(status.backgroundReady,true);assert.equal(status.capabilities.create,true);
  const [first,second]=await Promise.all([s.api('POST',`/api/channels/${s.channel.id}/native/create`,{}),s.api('POST',`/api/channels/${s.channel.id}/native/create`,{})]);
  assert.equal(created,1);assert.equal(first.threadId,second.threadId);assert.equal(first.threadId,s.transport.threadId);assert.equal(s.transport.sent.length,0);
  const binding=s.store.get<any>('native_bindings',s.channel.id);assert.equal(binding.createdByMorrow,true);assert.equal(binding.projectId,s.project.id);
  const actions=s.store.all<any>('events').map(event=>event.action);assert(actions.includes('native.creation-requested'));assert(actions.includes('native.created'));
  const receipt=await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text:'Native first input',requestId:randomUUID()});assert.equal(receipt.state,'accepted');assert.equal(s.transport.sent.length,1);assert.equal(s.transport.sent[0].workOptions,undefined);
}finally{await s.cleanup();}});
test('an explicitly selected native scope inherits App permissions and attaches scoped work tools to the same task',async()=>{const s=await setup();try{
  await s.native.bind(s.channel.id,s.transport.threadId);s.transport.emit({currentPermissions:{sandboxPolicy:{type:'dangerFullAccess'}}});
  await s.api('POST',`/api/channels/${s.channel.id}/action`,{action:'resume'},409);
  await s.api('PATCH',`/api/channels/${s.channel.id}`,{permission:'native'});await s.engine.action(s.channel.id,'resume');
  assert.equal(s.transport.sent.length,1);assert.deepEqual(s.transport.sent[0].workOptions,{approvalPolicy:'on-request',approvalsReviewer:'auto_review'});assert.match(s.transport.sent[0].text,/--operation context/);const run=s.store.all<any>('runs').find(r=>r.source==='morrow-schedule');assert.equal(run.sessionId,s.transport.threadId);
  const context=JSON.parse(readFileSync(join(s.home,'runs',run.id,'agent-context.json'),'utf8'));const response=await fetch(context.url,{method:'POST',headers:{Authorization:`Bearer ${context.token}`,'Content-Type':'application/json'},body:JSON.stringify({operation:'context',input:{}})});assert.equal(response.status,200);assert.equal((await response.json()).project.id,s.project.id);
  completeWork(s,nextWork('wait',60));assert.equal(s.store.get<any>('runs',run.id).status,'completed');const expired=await fetch(context.url,{method:'POST',headers:{Authorization:`Bearer ${context.token}`,'Content-Type':'application/json'},body:JSON.stringify({operation:'context',input:{}})});assert.equal(expired.status,409);
}finally{await s.cleanup();}});
test('an explicitly recreated empty task retains its audit; uncertain sends and existing history never permit replacement',async()=>{const s=await setup();try{
  let created=0;const originalRead=s.transport.readThread.bind(s.transport);let missing='';
  Object.assign(s.transport,{backgroundReady:true,readThread:async(id:string)=>{if(id===missing)throw new Error('no rollout found for thread id '+id);return originalRead(id);},createThread:async()=>{created++;s.transport.threadId=randomUUID();s.transport.snapshot={...s.transport.snapshot,threadId:s.transport.threadId,state:{turns:[],requests:[],cwd:s.project.path}};return originalRead(s.transport.threadId);}});
  const first=await s.api('POST',`/api/channels/${s.channel.id}/native/create`,{});missing=first.threadId;
  let view=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(view.canRecreateEmpty,true);assert.equal(created,1);
  const replacement=await s.api('POST',`/api/channels/${s.channel.id}/native/create`,{});assert.notEqual(replacement.threadId,first.threadId);assert.equal(created,2);assert(s.store.all<any>('events').some(event=>event.action==='native.empty-recreated'&&event.changes?.before?.threadId===first.threadId));
  missing=replacement.threadId;s.store.put('native_outbox',{id:'uncertain',threadId:missing,state:'unknown'});
  view=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(view.canRecreateEmpty,false);
  await s.api('POST',`/api/channels/${s.channel.id}/native/create`,{});assert.equal(created,2);
}finally{await s.cleanup();}});
const nextWork=(state='continue',waitMinutes?:number)=>'完成实际验证。\n```morrow-next\n'+JSON.stringify({state,focus:'登录体验',reason:'上次验证发现可复现的问题',nextStep:state==='needs_input'?'先修登录还是导入？':'验证登录错误提示',...(waitMinutes?{waitMinutes}:{})})+'\n```';
const completeWork=(s:any,text:string)=>s.transport.emit({turns:s.transport.snapshot.state.turns.map((turn:any)=>({...turn,status:'completed',items:[...turn.items,{id:randomUUID(),type:'agentMessage',phase:'final_answer',text}]}))});
test('a reconnected shared projection with a reset counter finishes the same native run and preserves its history',async()=>{const s=await setup();try{
  s.transport.snapshot.revision=500;await s.native.bind(s.channel.id,s.transport.threadId);await s.engine.action(s.channel.id,'resume');const run=s.store.all<any>('runs')[0];
  s.transport.snapshot={...s.transport.snapshot,ownerClientId:'shared:host:new-connection',revision:0};completeWork(s,nextWork('wait',60));
  assert.equal(s.store.get<any>('runs',run.id).status,'completed');assert.match(s.store.runText(run.id,'final'),/完成实际验证/);assert.equal(s.native.binding(s.channel.id)?.threadId,s.transport.threadId);assert.equal(s.store.all('runs').length,1);
}finally{await s.cleanup();}});
test('a native legacy needsHuman report cannot disable a registered release wait or override a manual pause',async()=>{const s=await setup();try{
  await s.native.bind(s.channel.id,s.transport.threadId);await s.engine.action(s.channel.id,'resume');const run=s.store.all<any>('runs')[0];const deadline=new Date(Date.now()+3600000).toISOString();
  s.store.put('loop_waits',{id:s.channel.id,projectId:s.project.id,runId:run.id,watchIds:[],releaseIds:[],deadline,reason:'等待上线确认',status:'waiting'});
  completeWork(s,'已准备好，等待上线确认。\n```morrow-report\n'+JSON.stringify({summary:'等待上线确认',items:[],knowledge:[],nextCheckMinutes:60,needsHuman:true})+'\n```\n'+nextWork('wait',60));
  assert.equal(s.engine.control(s.channel.id).enabled,true);assert.equal(s.store.get<any>('channels',s.channel.id).status,'waiting');assert.equal(s.store.get<any>('channels',s.channel.id).nextRunAt,deadline);
  await s.engine.action(s.channel.id,'pause');s.engine.loop.signal(s.channel.id,'receipt','发布结果');assert.equal(s.engine.control(s.channel.id).enabled,false);assert.equal(s.store.get<any>('channels',s.channel.id).nextRunAt,'');
}finally{await s.cleanup();}});
test('start prepares one task, native decisions drive follow-up and user guidance resumes the same work',async()=>{const s=await setup();try{
  let creates=0;Object.assign(s.transport,{backgroundReady:true,createThread:async()=>{creates++;s.transport.emit({turns:[]});return s.transport.readThread(s.transport.threadId);}});
  await Promise.all([s.engine.action(s.channel.id,'resume'),s.engine.action(s.channel.id,'resume')]);assert.equal(creates,1);assert.equal(s.transport.sent.length,1);assert.match(s.transport.sent[0].text,/自主选出最值得推进/);assert.equal(s.engine.control(s.channel.id).enabled,true);
  completeWork(s,nextWork());let channel=s.store.get<any>('channels',s.channel.id);assert.equal(channel.work.state,'continue');assert(Date.parse(channel.nextRunAt)-Date.now()<31000);assert.equal(s.store.all<any>('runs')[0].status,'completed');assert.equal(s.store.snapshot([]).channels[0].autonomyEnabled,true);
  s.store.put('channels',{...channel,nextRunAt:new Date(0).toISOString()});s.engine.tick();for(let i=0;i<100&&s.transport.sent.length<2;i++)await new Promise(done=>setTimeout(done,5));assert.equal(s.transport.sent.length,2);assert.match(s.transport.sent[1].text,/验证登录错误提示/);
  completeWork(s,nextWork('needs_input'));channel=s.store.get<any>('channels',s.channel.id);assert.equal(channel.work.awaitingReply,true);assert.equal(s.engine.control(s.channel.id).enabled,false);
  const requestId=randomUUID();await s.native.send(s.channel.id,'先修登录，保留现有布局',requestId);assert.equal(s.transport.sent.at(-1)?.text,'先修登录，保留现有布局');assert.equal(s.engine.control(s.channel.id).enabled,true);assert.equal(s.store.get<any>('channels',s.channel.id).work.awaitingReply,false);
  const guided=s.store.all<any>('events').filter(event=>event.action==='channel.guided').length;await s.native.send(s.channel.id,'先修登录，保留现有布局',requestId);assert.equal(s.store.all<any>('events').filter(event=>event.action==='channel.guided').length,guided);assert.equal(creates,1);
  assert.equal((await s.native.conversation(s.channel.id,{})).items.filter(item=>item.autonomousContext).length,2);
}finally{await s.cleanup();}});
test('wait decisions persist while manual pause prevents later chat from reactivating work',async()=>{const s=await setup();try{
  await s.native.bind(s.channel.id,s.transport.threadId);await s.engine.action(s.channel.id,'resume');completeWork(s,nextWork('wait',120));let channel=s.store.get<any>('channels',s.channel.id);assert.equal(channel.work.waitMinutes,120);assert(Date.parse(channel.nextRunAt)-Date.now()>119*60000);
  await s.engine.action(s.channel.id,'pause');await s.native.send(s.channel.id,'只是问问当前进展',randomUUID());assert.equal(s.engine.control(s.channel.id).enabled,false);assert.equal(s.store.get<any>('channels',s.channel.id).nextRunAt,'');
  const saved=s.store.get<any>('channels',s.channel.id).work;assert.equal(saved.runId,s.store.all<any>('runs').find(run=>run.source==='morrow-schedule').id);assert(s.store.all<any>('events').some(event=>event.action==='channel.next-step'));
}finally{await s.cleanup();}});
test('unknown guidance waits for native confirmation and cannot override a subsequent pause',async()=>{const s=await setup();try{
  await s.native.bind(s.channel.id,s.transport.threadId);await s.engine.action(s.channel.id,'resume');completeWork(s,nextWork('needs_input'));s.transport.failure=true;const requestId=randomUUID();const receipt=await s.native.send(s.channel.id,'先修登录',requestId);assert.equal(receipt.state,'unknown');assert.equal(s.engine.control(s.channel.id).enabled,false);
  await s.engine.action(s.channel.id,'pause');s.transport.emit({turns:[...s.transport.snapshot.state.turns,{turnId:'later-confirmed',status:'completed',items:[{id:'late-user',type:'userMessage',clientId:requestId,content:[{type:'text',text:'先修登录'}]}]}]});assert.equal(s.store.get<any>('native_outbox',s.channel.id+':'+requestId).state,'accepted');assert.equal(s.engine.control(s.channel.id).enabled,false);assert.equal(s.store.get<any>('channels',s.channel.id).work.awaitingReply,false);
}finally{await s.cleanup();}});
test('a reply from the native App also releases an agent question without starting a second session',async()=>{const s=await setup();try{
  await s.native.bind(s.channel.id,s.transport.threadId);await s.engine.action(s.channel.id,'resume');completeWork(s,nextWork('needs_input'));
  s.transport.emit({turns:[...s.transport.snapshot.state.turns,{turnId:'app-guidance',status:'inProgress',items:[{id:'app-user',type:'userMessage',content:[{type:'text',text:'先修登录'}]}]}]});
  assert.equal(s.engine.control(s.channel.id).enabled,true);assert.equal(s.store.get<any>('channels',s.channel.id).work.awaitingReply,false);assert.equal(s.transport.sent.length,1);
}finally{await s.cleanup();}});
test('an obsolete direction never installs the old next step',async()=>{const s=await setup();try{
  await s.native.bind(s.channel.id,s.transport.threadId);await s.engine.action(s.channel.id,'resume');const channel=s.store.get<any>('channels',s.channel.id);s.store.put('channels',{...channel,goal:'先解决用户最新指定的问题'});completeWork(s,nextWork('needs_input'));assert.equal(s.store.get<any>('channels',s.channel.id).work,undefined);assert.equal(s.engine.control(s.channel.id).enabled,true);assert(s.store.all<any>('events').some(event=>event.action==='channel.plan-outdated'));
}finally{await s.cleanup();}});
test('follower-only and failed background connection cannot claim native creation is available',async()=>{const s=await setup();try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/create`,{},409);assert.equal(s.store.all('native_bindings').length,0);
  Object.assign(s.transport,{backgroundReady:true,createThread:async()=>{throw new Error('should not run')},connect:async()=>{throw new Error('ambiguous native host')}});
  const status=await s.api('GET','/api/native/status');assert.equal(status.connected,false);assert.equal(status.capabilities.create,false);assert.match(status.detail,/ambiguous/);
}finally{await s.cleanup();}});
test('native binding uses the same project task, persists full original messages, deduplicates sends and preserves sessions on settings edits',async()=>{const s=await setup();try{
  const list=await s.api('GET',`/api/channels/${s.channel.id}/native/threads`);assert.equal(list.threads[0].id,s.transport.threadId);
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:'other-project'},404);
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});
  const text='  原样输入\n不要添加调度上下文  ';const requestId=randomUUID();const receipt=await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text,requestId});assert.equal(receipt.state,'accepted');assert.equal(s.transport.sent[0].text,text);
  await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text,requestId});assert.equal(s.transport.sent.length,1);
  await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text:'different',requestId},409);
  const conversation=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(conversation.items[0].text,text);assert.equal(conversation.thread.activeTurnId,receipt.turnId);
  const updated=await s.api('PATCH',`/api/channels/${s.channel.id}`,{model:'native-model',permission:'workspace-write'});assert.equal(updated.sessionId,s.transport.threadId);
  await s.api('POST',`/api/channels/${s.channel.id}/messages`,{text:'old-note'},409);
  assert.equal(s.store.all<any>('runs')[0].source,'morrow-chat');assert.equal(s.engine.budgetCount(s.channel.id),0);assert(s.store.all('native_events').length>0);assert.equal(s.store.all<any>('native_outbox')[0].text,text);
}finally{await s.cleanup();}});
test('native external history remains complete, paged, revision safe and available offline',async()=>{const s=await setup();try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});
  const long='外部完整消息'.repeat(4000);const turns=Array.from({length:185},(_,i)=>({turnId:`turn-${i}`,status:'completed',items:[{id:`item-${i}`,type:'agentMessage',text:i===184?long:`message ${i}`}]}));s.transport.emit({turns});
  const page=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation?limit=80`);assert.equal(page.items.length,80);assert.equal(page.items.at(-1).text,long);assert.equal(page.hasMore,true);
  const older=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation?limit=80&before=${page.cursor}`);assert.equal(older.items.length,80);assert.equal(new Set([...page.items,...older.items].map(row=>row.id)).size,160);
  s.native.ingest({...s.transport.snapshot,revision:0,state:{turns:[]}});assert.equal(s.store.all<any>('native_items').filter(row=>row.present).length,185);
  s.transport.connected=false;const cached=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(cached.status.connected,false);assert.equal(cached.items.at(-1).text,long);assert.equal(s.store.all('runs').length,185);assert(s.store.all<any>('runs').every(run=>run.source==='native-app'));assert.equal(s.engine.budgetCount(s.channel.id),0);
}finally{await s.cleanup();}});
test('unknown sends are never retried and native approvals and interrupt are scoped to the active turn',async()=>{const s=await setup();try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});s.transport.failure=true;const requestId=randomUUID();const first=await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text:'hello',requestId});assert.equal(first.state,'unknown');await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text:'hello',requestId});assert.equal(s.transport.sent.length,1);
  s.transport.emit({turns:[{turnId:'external-turn',status:'inProgress',items:[]}],requests:[{id:42,method:'item/commandExecution/requestApproval',params:{threadId:s.transport.threadId,turnId:'external-turn'}}]});
  await s.api('POST',`/api/channels/${s.channel.id}/native/interrupt`,{turnId:'wrong'},409);await s.api('POST',`/api/channels/${s.channel.id}/native/interrupt`,{turnId:'external-turn'});assert.deepEqual(s.transport.interruptions,['external-turn']);
  await s.api('POST',`/api/channels/${s.channel.id}/native/respond`,{requestId:'wrong',response:{decision:'accept'}},409);await s.api('POST',`/api/channels/${s.channel.id}/native/respond`,{requestId:'42',response:{decision:'decline'}});assert.equal(s.transport.answers[0].requestId,42);assert.equal(s.transport.answers[0].kind,'command');
}finally{await s.cleanup();}});
test('native bounded scheduling inherits compatible settings, observes completion, rejects unsafe scope and never starts a CLI',async()=>{const s=await setup();try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});
  await s.api('PATCH',`/api/channels/${s.channel.id}`,{permission:'read-only'});
  s.transport.emit({currentPermissions:{sandboxPolicy:{type:'dangerFullAccess'}}});await s.api('POST',`/api/channels/${s.channel.id}/action`,{action:'run'},409);assert.equal(s.transport.sent.length,0);
  s.transport.emit({currentPermissions:{sandboxPolicy:{type:'readOnly'}}});await s.api('POST',`/api/channels/${s.channel.id}/action`,{action:'run'});assert.equal(s.transport.sent.length,1);assert.equal(s.engine.active.size,0);const run=s.store.all<any>('runs')[0];assert.equal(run.executionOwner,'codex-app');assert.equal(run.permission,'native');assert.deepEqual(s.transport.sent[0].workOptions?.sandboxPolicy,{type:'readOnly',networkAccess:false});
  const turns=s.transport.snapshot.state.turns.map((turn:any)=>({...turn,status:'completed',items:[...turn.items,{id:'native-final',type:'agentMessage',text:'原生 App 中完成的同一轮次。'}]}));s.transport.emit({turns});assert.equal(s.store.get<any>('runs',run.id).status,'completed');assert.match(s.store.runText(run.id,'final'),/同一轮次/);assert.equal(s.store.all('items').length,0);
}finally{await s.cleanup();}});
test('per-thread disconnect disables sending, same-revision reconnect clears errors without duplicate writes, and partial history retains older items',async()=>{const s=await setup();try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});s.transport.emit({turns:[{turnId:'old',status:'completed',items:[{id:'old-message',type:'agentMessage',text:'older'}]},{turnId:'new',status:'completed',items:[{id:'new-message',type:'agentMessage',text:'latest'}]}]});
  const before=s.store.all('native_events').length;s.transport.readFailure=true;const disconnected=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(disconnected.status.connected,false);assert.equal(disconnected.status.capabilities.send,false);s.transport.readFailure=false;const reconnected=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(reconnected.status.connected,true);assert.equal(s.store.all('native_events').length,before);
  s.transport.emit({turnHistory:{history:{isComplete:false,islands:[{entries:[{value:'new'}]}],entitiesByKey:{new:s.transport.snapshot.state.turns[1]}}}});const partial=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.deepEqual(partial.items.map((item:any)=>item.text),['older','latest']);
}finally{await s.cleanup();}});
test('daemon restart observes external native work without taking ownership or interrupting App, while definitive scheduler rejection settles',async()=>{const s=await setup();let restarted:Awaited<ReturnType<typeof startServer>>|undefined;try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});const receipt=await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text:'native chat',requestId:randomUUID()});const run=s.store.all<any>('runs')[0];await s.close();assert.equal(s.transport.interruptions.length,0);s.transport.connected=true;restarted=await startServer({home:s.home,port:0,nativeTransport:s.transport});await restarted.native.conversation(s.channel.id,{});assert.equal(restarted.native.scheduled.size,0);assert.equal(restarted.store.get<any>('runs',run.id).status,'running');s.transport.emit({turns:s.transport.snapshot.state.turns.map((turn:any)=>({...turn,status:'completed',items:[...turn.items,{id:'final',type:'agentMessage',phase:'commentary',text:'not final'},{id:'final-answer',type:'agentMessage',phase:'final_answer',text:'native final'}]}))});assert.equal(restarted.store.get<any>('runs',run.id).status,'completed');assert.equal(restarted.store.runText(run.id,'final'),'native final');assert.equal(restarted.engine.budgetCount(s.channel.id),0);
  s.transport.definitiveFailure=true;await restarted.engine.action(s.channel.id,'run');const failed=restarted.store.all<any>('runs').find(row=>row.source==='morrow-schedule');assert.equal(failed.status,'failed');assert.equal(restarted.native.scheduled.size,0);assert.equal(s.transport.interruptions.length,0);assert(receipt.turnId);
}finally{await restarted?.close();await s.cleanup();}});
test('native image API persists selected bytes and sends opaque attachments once without changing image-only input',async()=>{const s=await setup();try{
  const path=join(s.root,'pixel.png');writeFileSync(path,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jxIoAAAAASUVORK5CYII=','base64'));await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});const images=await s.api('POST',`/api/channels/${s.channel.id}/native/images`,{paths:[path]});const requestId=randomUUID();await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text:'',requestId,attachments:images});assert.equal(s.transport.sent[0].text,'');assert.equal(s.transport.sent[0].images?.length,1);assert.notEqual(s.transport.sent[0].images?.[0].path,path);await s.api('POST',`/api/channels/${s.channel.id}/native/messages`,{text:'',requestId,attachments:images.map((image:any)=>({...image,name:'presentation-only'}))});assert.equal(s.transport.sent.length,1);const conversation=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);const loaded=await s.api('GET',`/api/channels/${s.channel.id}/native/images/${conversation.items[0].id}/1`);assert.match(loaded.dataUrl,/^data:image\/png;base64,/);
}finally{await s.cleanup();}});
test('actual App steering messages remain user input, reconcile unknown delivery, deduplicate canonical messages and reproject old snapshots',async()=>{const s=await setup();try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});const requestId=randomUUID(),turnId=randomUUID(),serverId=randomUUID();const text='  Morrow 双端追加验收\n保留原文  ';const createdAt='2026-09-07T08:30:00.000Z';const steering={type:'steeringUserMessage',id:randomUUID(),targetTurnId:turnId,targetTurnStartedAtMs:1788769000000,status:'accepted',serverUserMessageId:serverId,clientUserMessageId:requestId,input:[{type:'text',text}],attachments:[],restoreMessage:{id:requestId,text,context:[],cwd:s.project.path,createdAt},compareKey:'native-comparison-key'};
  s.store.put('native_outbox',{id:`${s.channel.id}:${requestId}`,requestId,channelId:s.channel.id,projectId:s.project.id,threadId:s.transport.threadId,text,state:'unknown',source:'chat',createdAt});
  s.transport.emit({turns:[{turnId,status:'inProgress',items:[steering,{type:'steered',id:serverId}]}]});let view=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(view.items.length,1);assert.equal(view.items[0].role,'user');assert.equal(view.items[0].text,text);assert.equal(view.items[0].createdAt,createdAt);assert.deepEqual(view.items[0].raw,steering);assert.equal(s.store.get<any>('native_outbox',`${s.channel.id}:${requestId}`).state,'accepted');assert.equal(s.store.get<any>('native_outbox',`${s.channel.id}:${requestId}`).turnId,turnId);
  const run=s.store.all<any>('runs')[0];assert.equal(s.store.runText(run.id,'prompt'),text);const existing=s.store.get<any>('native_items',view.items[0].id);s.store.put('native_items',{...existing,role:'tool',text:''});const thread=s.store.get<any>('native_threads',s.transport.threadId);s.store.put('native_threads',{...thread,projectionVersion:1});s.native.observed.clear();s.native.ingest(structuredClone(s.transport.snapshot));view=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(view.items[0].role,'user');assert.equal(view.items[0].text,text);
  const canonical={type:'userMessage',id:serverId,clientId:requestId,content:[{type:'text',text}]};s.transport.emit({turns:[{turnId,status:'inProgress',items:[steering,{type:'steered',id:serverId},canonical]}]});view=await s.api('GET',`/api/channels/${s.channel.id}/native/conversation`);assert.equal(view.items.length,1);assert.equal(view.items[0].type,'userMessage');assert.equal(view.items[0].text,text);assert.equal(s.store.runText(run.id,'prompt'),text);assert.equal(s.transport.sent.length,0);
}finally{await s.cleanup();}});
test('streaming a long native history journals every delta while coalescing only projections and flushing on close',async()=>{const s=await setup();try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});const items=Array.from({length:1066},(_,index)=>({id:`item-${index}`,type:'agentMessage',phase:'commentary',text:`${index}:`+'history '.repeat(512)}));const state={turns:[{turnId:'large-turn',status:'inProgress',items}],requests:[]};let snapshot={...s.transport.snapshot,revision:s.transport.snapshot.revision+1,state};s.native.ingest(snapshot,true);
  const baselineItem=s.store.get<any>('native_items',[...s.native.itemCache.get(snapshot.threadId)!.values()][0].id);const beforeEvents=s.store.all('native_events').length;const counts={threads:0,items:0,scans:0};const put=s.store.put.bind(s.store);const rows=s.store.nativeRows.bind(s.store);s.store.put=((table:string,row:any)=>{if(table==='native_threads')counts.threads++;if(table==='native_items')counts.items++;return put(table,row);}) as typeof s.store.put;s.store.nativeRows=((table:any,id:string)=>{if(table==='native_items')counts.scans++;return rows(table,id);}) as typeof s.store.nativeRows;
  for(let index=1;index<=40;index++){const change={type:'patches' as const,baseRevision:snapshot.revision,revision:snapshot.revision+1,patches:[{op:'replace' as const,path:['turns',0,'items',1065,'text'],value:`stream ${index}`} ]};snapshot={...snapshot,revision:change.revision,syncedAt:new Date().toISOString(),state:applyDesktopPatches(snapshot.state,change.patches) as typeof state};s.native.queueSnapshot(snapshot,change);}
  assert.equal(s.store.all('native_events').length-beforeEvents,40);assert.equal(counts.threads,0);assert.equal(counts.items,0);s.native.flushPending(snapshot.threadId);assert.equal(counts.items,1);assert.equal(counts.threads,0);assert.equal(counts.scans,0);assert.equal(s.native.threadCache.get(snapshot.threadId)?.revision,snapshot.revision);assert.deepEqual(s.store.get('native_items',baselineItem.id),baselineItem);
  const lastChange={type:'patches' as const,baseRevision:snapshot.revision,revision:snapshot.revision+1,patches:[{op:'replace' as const,path:['turns',0,'items',1065,'text'],value:'final pending text'}]};snapshot={...snapshot,revision:lastChange.revision,state:applyDesktopPatches(snapshot.state,lastChange.patches) as typeof state};s.native.queueSnapshot(snapshot,lastChange);s.native.close();assert.equal(s.native.pendingSnapshots.size,0);assert.equal(s.store.get<any>('native_threads',snapshot.threadId).revision,snapshot.revision);assert.equal(s.store.nativeRows<any>('native_items',snapshot.threadId).find(item=>item.raw.id==='item-1065').text,'final pending text');assert.equal(s.store.all<any>('native_events').filter(event=>event.kind==='native.patch').length,41);assert.equal(s.transport.interruptions.length,0);
}finally{await s.cleanup();}});
test('unflushed native deltas recover from the durable journal before App reconnect',async()=>{const s=await setup();let recovered:NativeConversations|undefined;try{
  await s.api('POST',`/api/channels/${s.channel.id}/native/bind`,{threadId:s.transport.threadId});const state={turns:[{turnId:'recover-turn',status:'inProgress',items:[{id:'recover-item',type:'agentMessage',phase:'commentary',text:'before'}]}],requests:[]};const initial={...s.transport.snapshot,revision:s.transport.snapshot.revision+1,state};s.native.ingest(initial,true);const change={type:'patches' as const,baseRevision:initial.revision,revision:initial.revision+1,patches:[{op:'replace' as const,path:['turns',0,'items',0,'text'],value:'durable after crash'}]};const latest={...initial,revision:change.revision,state:applyDesktopPatches(initial.state,change.patches)};s.native.queueSnapshot(latest,change);assert.equal(s.store.get<any>('native_threads',initial.threadId).revision,initial.revision);
  // Simulate process death before its projection timer, leaving the committed delta.
  for(const timer of s.native.pendingTimers.values())clearTimeout(timer);s.native.pendingTimers.clear();s.native.pendingSnapshots.clear();s.native.closed=true;s.transport.connected=false;recovered=new NativeConversations(s.store,s.engine,s.transport);recovered.recoverCheckpoint(initial.threadId);const view=await recovered.conversation(s.channel.id,{});assert.equal(view.status.connected,false);assert.equal(view.items[0].text,'durable after crash');assert.equal(s.store.get<any>('native_threads',initial.threadId).revision,latest.revision);assert.equal(s.transport.interruptions.length,0);
}finally{recovered?.close();await s.cleanup();}});
